#################### 必填 ####################
## chromedriver 可执行文件路径
# 仅为示例，请根据自己设备上的路径进行填写。Windows下注意要用双反斜杠。
chrome_driver_path: "C:\\Program Files\\Google\\Chrome\\Application\\chromedriver.exe"

## 一卡通号（将 22000000x 替换为您的一卡通号）
# 如需要添加打卡账号，请按照此格式（- "xxx"）向下添加。
# 如只有一个用户，请删除多余的行，下同。【注意保持几个列表项数一致，且彼此匹配】
user_id:
    - "220000000"
    - "220000001"

## 统一身份认证密码（将 ****** 替换为统一身份认证密码）
password:
    - "******"
    - "******"

#################### 可选 ####################
## 是否需要发送邮件通知打卡结果（yes/no）
notification:
    - "no"
    - "no"

## 只有尝试打卡失败后，才发送邮件（yes/no）
notify_failure_only:
    - "no"
    - "no"

## 发送打卡状态的邮箱地址（将 USER_NAME@seu.edu.cn 替换为您的邮箱地址）
from_addr: "USER_NAME@seu.edu.cn"

# 发送打卡状态的邮箱密码（将 ****** 替换为您的邮箱登录密码）
email_password: "******"

## 发送打卡状态的邮箱的 SMTP 服务器地址
#一般为 smtp.<邮箱后缀> 若不清楚可在网上查询所用邮箱的SMTP服务器地址
smtp_server: "smtp.seu.edu.cn"

## 发送打卡状态的邮箱的 smtp 服务器端口号
# 一般为25，为保证发送成功率，建议使用支持SSL协议的端口，具体端口号可在网上查询
port: 25

## 接收打卡状态的邮箱地址
to_addr:
    - "name1@example.com"
    - "name2@example.com"
